"""Generate the CC0 crate example: a unit cube OBJ with normals and UVs, its MTL,
and a 64x64 base-color PNG. Standard library only; deterministic output.

Run from anywhere:

    python examples/crate/make_crate_assets.py

The generated files are committed beside this script so a fresh clone can run
`scripts/compile_prop.py examples/crate/crate.json` without generating anything.
Re-running rewrites them byte-for-byte. Public domain (CC0 1.0).
"""
from __future__ import annotations

import struct
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
MATERIAL = "MAT-Crate"

# Eight corners of a unit cube standing on Z=0, centred on X/Y (Blender is Z-up).
CORNERS = [
    (-0.5, -0.5, 0.0), (0.5, -0.5, 0.0), (0.5, 0.5, 0.0), (-0.5, 0.5, 0.0),
    (-0.5, -0.5, 1.0), (0.5, -0.5, 1.0), (0.5, 0.5, 1.0), (-0.5, 0.5, 1.0),
]
# Each face: four corner indices (counter-clockwise seen from outside) and its
# outward normal. UVs lay the six faces out as a 3x2 grid so no island overlaps.
FACES = [
    ((0, 1, 5, 4), (0.0, -1.0, 0.0)),   # front  (-Y)
    ((1, 2, 6, 5), (1.0, 0.0, 0.0)),    # right  (+X)
    ((2, 3, 7, 6), (0.0, 1.0, 0.0)),    # back   (+Y)
    ((3, 0, 4, 7), (-1.0, 0.0, 0.0)),   # left   (-X)
    ((4, 5, 6, 7), (0.0, 0.0, 1.0)),    # top    (+Z)
    ((3, 2, 1, 0), (0.0, 0.0, -1.0)),   # bottom (-Z)
]


def write_obj() -> None:
    lines = [
        "# CC0 1.0 public domain. Generated by examples/crate/make_crate_assets.py.",
        "# Unit cube, 1 m tall, base on Z=0, six UV islands in a 3x2 grid.",
        "mtllib crate.mtl",
        "o Crate",
    ]
    lines += ["v {0:.6f} {1:.6f} {2:.6f}".format(*c) for c in CORNERS]
    uvs: list[tuple[float, float]] = []
    for index in range(len(FACES)):
        column, row = index % 3, index // 3
        u0, v0 = column / 3.0, row / 2.0
        u1, v1 = (column + 1) / 3.0, (row + 1) / 2.0
        uvs += [(u0, v0), (u1, v0), (u1, v1), (u0, v1)]
    lines += ["vt {0:.6f} {1:.6f}".format(*uv) for uv in uvs]
    lines += ["vn {0:.6f} {1:.6f} {2:.6f}".format(*normal) for _, normal in FACES]
    lines += ["usemtl " + MATERIAL, "s off"]
    for index, (corners, _) in enumerate(FACES):
        face = " ".join(
            "{0}/{1}/{2}".format(corner + 1, index * 4 + k + 1, index + 1)
            for k, corner in enumerate(corners)
        )
        lines.append("f " + face)
    (HERE / "crate.obj").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def write_mtl() -> None:
    text = "\n".join([
        "# CC0 1.0 public domain. Generated by examples/crate/make_crate_assets.py.",
        "newmtl " + MATERIAL,
        "Kd 0.800000 0.800000 0.800000",
        "Ks 0.000000 0.000000 0.000000",
        "Ns 10.000000",
        "d 1.000000",
        "illum 1",
        "map_Kd crate_basecolor.png",
    ]) + "\n"
    (HERE / "crate.mtl").write_text(text, encoding="utf-8", newline="\n")


def png_bytes(width: int, height: int, rows: list[bytes]) -> bytes:
    def chunk(kind: bytes, payload: bytes) -> bytes:
        body = kind + payload
        return struct.pack(">I", len(payload)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)  # 8-bit RGB
    raw = b"".join(b"\x00" + row for row in rows)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header)
            + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))


def write_basecolor() -> None:
    """Neutral wood base color; directional shading belongs to the renderer."""
    size = 64
    rows = [bytes((150, 105, 62)) * size for _ in range(size)]
    (HERE / "crate_basecolor.png").write_bytes(png_bytes(size, size, rows))


def main() -> int:
    write_obj()
    write_mtl()
    write_basecolor()
    for name in ("crate.obj", "crate.mtl", "crate_basecolor.png"):
        print("wrote", HERE / name, (HERE / name).stat().st_size, "bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
